### ISSUE TITLE
New execution after flushed cache

### ISSUE THREAD

**Issue by lars85** [ttreeagency/Scheduler#11]
The execution times of the tasks are stored in Data/Temporary/Production/Data/Cache/Data/TtreeScheduler_DynamicTaskLastExecution/.

With ./flow flow:cache:flush the whole directory gets cleared and (I guess) the scheduler does not now the last execution time anymore of the tasks.

With the next run of ./flow task:run it executes all tasks again (this is the issue).

Solution: Save the execution times in Data/Persistence.

**Comment by dfeyer** [comment]
👍 we can use a persistent cache
