### ISSUE TITLE
Missing Transient Annoation for CronExpression causes Exception #1355480641

### ISSUE THREAD

**Issue by psycodepath** [ttreeagency/Scheduler#2]
Hi, i tried to get this package back to work. But i got an Exception (#1355480641) due to invalid [doctrine relation setting](https://github.com/ttreeagency/Scheduler/blob/master/Classes/Ttree/Scheduler/Domain/Model/Task.php#L76) for the property CronExpression I think since this property gets constructed in the getter, it should not be persisted.

**Comment by dfeyer** [comment]
@psycodepath Thanks for reporting and sorry for the response delay
