### ISSUE TITLE
Regression if tasks can be ran in parallel (default behavior)?

### ISSUE THREAD

**Issue by radmiraal** [ttreeagency/Scheduler#20]
It seems lik f676afc4bf2611300190e6e8e204b3fc197b8e91 introduced a regression because it sets a lock if `allowParallelExecution` is false. On the end of the task run it will call `->release()` on the lock, but if `allowParallelExecution` is true the lock variable will be empty so a `Call to a member function release() on null` is thrown.

Probably this is as easy a adding a simple if condition around the `->release()` call, didn't dig into it

**Comment by svparijs** [comment]
Currently ran into the same issue.
